name: Build and Publish Firmware

on:
  push:
    tags:
      - 'v*' # Скрипт запустится автоматически при git push origin v...

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Разрешение на создание ветки gh-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ESPHome
        run: pip install esphome

      - name: Compile ESPHome Firmware
        # Убедитесь, что имя файла совпадает с вашим yaml
        run: esphome compile src/main.yaml

      - name: Prepare Files for Pages
        run: |
          mkdir public
          # Берем имя тега напрямую из Git (например, v2026.4.0)
          VERSION="${{ github.ref_name }}"
          BIN_NAME="stove-${VERSION}.bin"
          
          # Копируем скомпилированную прошивку
          cp .esphome/build/stove/.pioenvs/stove/firmware.bin public/$BIN_NAME
          
          # Считаем MD5
          MD5_HASH=$(md5sum public/$BIN_NAME | awk '{ print $1 }')
          
          # Создаем manifest.json для вашего устройства
          cat <<EOF > public/manifest.json
          {
            "version": "$VERSION",
            "ota_url": "https://alaltitov.github.io/stove/$BIN_NAME",
            "md5": "$MD5_HASH"
          }
          EOF
          
          # Создаем esphome-manifest.json
          cat <<EOF > public/esphome-manifest.json
          {
            "name": "alaltitov.stove",
            "version": "$VERSION",
            "builds": [
              {
                "chipFamily": "ESP32-S3",
                "parts": [
                  { "path": "https://alaltitov.github.io/stove/$BIN_NAME", "offset": 65536 }
                ]
              }
            ]
          }
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true # Очищает старые файлы, оставляя только актуальную прошивку
